import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import './globals.css'
import { NextAuthProvider } from './components/NextAuthProvider'
import Head from 'next/head'

const roboto = Roboto({
  style: ['normal', 'italic'],
  subsets: ['latin'],
  weight: ['400', '700']
})

export const metadata: Metadata = {
  title: 'Netflix Clone Next14',
  description: 'Generated by create next app',
}

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
  <html lang="en">
    <head>
			<link rel="shortcut icon" href='/favicon.ico' />
		</head>
    <body className={roboto.className}>
      <NextAuthProvider>
        {children}
      </NextAuthProvider>
    </body>
  </html>
  )
}
