import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import './globals.css'
import { NextAuthProvider } from './components/NextAuthProvider'
import { SpeedInsights } from '@vercel/speed-insights/next'

const roboto = Roboto({
  style: ['normal', 'italic'],
  subsets: ['latin'],
  weight: ['400', '700']
})

export const metadata: Metadata = {
  title: 'Netflix Clone Next14',
  description: 'Generated by create next app',
}

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
  <html lang="en">
		<link rel="shortcut icon" href='/favicon.ico' />
    <body className={roboto.className}>
      <NextAuthProvider>
        {children}
        <SpeedInsights />
      </NextAuthProvider>
    </body>
  </html>
  )
}
